### ISSUE TITLE
Bug : dateRange argument of function exchangesStack returns strange results 

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antares-rpackageViz#76]
While using the function exchangesStack : 

`prodStack(data_hourly_synthesis, stack = "eco2mix", areas = "37_h", dateRange = c("2018-01-08", "2018-01-21"), main = "Production stack", unit = "GWh",  interactive = FALSE, width = "100%", height = 500)`

I got a strange result which seems to also include the last timeStep of the studied horizon : 

![image](https://cloud.githubusercontent.com/assets/23483145/24650018/370fd8b0-1929-11e7-95f4-de673a4c518e.png)

**Comment by FrancoisGuillem** [comment]
Ca devrait être résolu maintenant. Tu peux vérifier s'il te plait ?

**Comment by baptsegu** [comment]
Merci :), ça marche
