### ISSUE TITLE
Bug : arguments height and width with heatmap

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antares-rpackageViz#77]
When inserting graphs in a rmarkdown documents with the function `plot()`, height and width arguments are not working.

![image](https://cloud.githubusercontent.com/assets/23483145/24650292/0401b05a-192a-11e7-88f8-56d81f30cf7a.png)

Note that for any other type of graph (time series, barplot, ...), width and height are returning the expected results.

**Comment by FrancoisGuillem** [comment]
Ca devrait êter résolu. Tu peux tester ?

**Comment by baptsegu** [comment]
C'est résolu
